DROP TABLE IF EXISTS allele_specific_copy_number;
DROP TABLE IF EXISTS alteration_driver_annotation;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS cancer_study;
DROP TABLE IF EXISTS cancer_study_tags;
DROP TABLE IF EXISTS clinical_attribute_meta;
DROP TABLE IF EXISTS clinical_event;
DROP TABLE IF EXISTS clinical_event_data;
DROP TABLE IF EXISTS clinical_patient;
DROP TABLE IF EXISTS clinical_sample;
DROP TABLE IF EXISTS cna_event;
DROP TABLE IF EXISTS copy_number_seg;
DROP TABLE IF EXISTS copy_number_seg_file;
DROP TABLE IF EXISTS data_access_tokens;
DROP TABLE IF EXISTS gene;
DROP TABLE IF EXISTS gene_alias;
DROP TABLE IF EXISTS gene_panel;
DROP TABLE IF EXISTS gene_panel_list;
DROP TABLE IF EXISTS generic_entity_properties;
DROP TABLE IF EXISTS geneset;
DROP TABLE IF EXISTS geneset_gene;
DROP TABLE IF EXISTS geneset_hierarchy_leaf;
DROP TABLE IF EXISTS geneset_hierarchy_node;
DROP TABLE IF EXISTS genetic_alteration;
DROP TABLE IF EXISTS genetic_entity;
DROP TABLE IF EXISTS genetic_profile;
DROP TABLE IF EXISTS genetic_profile_link;
DROP TABLE IF EXISTS genetic_profile_samples;
DROP TABLE IF EXISTS gistic;
DROP TABLE IF EXISTS gistic_to_gene;
DROP TABLE IF EXISTS info;
DROP TABLE IF EXISTS mut_sig;
DROP TABLE IF EXISTS mutation;
DROP TABLE IF EXISTS mutation_count_by_keyword;
DROP TABLE IF EXISTS mutation_event;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS reference_genome;
DROP TABLE IF EXISTS reference_genome_gene;
DROP TABLE IF EXISTS resource_definition;
DROP TABLE IF EXISTS resource_patient;
DROP TABLE IF EXISTS resource_sample;
DROP TABLE IF EXISTS resource_study;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS sample_cna_event;
DROP TABLE IF EXISTS sample_list;
DROP TABLE IF EXISTS sample_list_list;
DROP TABLE IF EXISTS sample_profile;
DROP TABLE IF EXISTS structural_variant;
DROP TABLE IF EXISTS type_of_cancer;
DROP TABLE IF EXISTS users;
CREATE TABLE allele_specific_copy_number (`mutation_event_id` Nullable(Int64),`genetic_profile_id` Nullable(Int64),`sample_id` Nullable(Int64),`ascn_integer_copy_number` Nullable(Int64),`ascn_method` Nullable(String),`ccf_expected_copies_upper` Nullable(Float64),`ccf_expected_copies` Nullable(Float64),`clonal` Nullable(String),`minor_copy_number` Nullable(Int64),`expected_alt_copies` Nullable(Int64),`total_copy_number` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE alteration_driver_annotation (`alteration_event_id` Nullable(Int64),`genetic_profile_id` Nullable(Int64),`sample_id` Nullable(Int64),`driver_filter` Nullable(String),`driver_filter_annotation` Nullable(String),`driver_tiers_filter` Nullable(String),`driver_tiers_filter_annotation` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE authorities (`email` Nullable(String),`authority` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE cancer_study (`cancer_study_id` Nullable(Int64),`cancer_study_identifier` Nullable(String),`type_of_cancer_id` Nullable(String),`name` Nullable(String),`description` Nullable(String),`public` Nullable(Int32),`pmid` Nullable(String),`citation` Nullable(String),`groups` Nullable(String),`status` Nullable(Int64),`import_date` Nullable(DateTime64(6)),`reference_genome_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE cancer_study_tags (`cancer_study_id` Nullable(Int64),`tags` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE clinical_attribute_meta (`attr_id` Nullable(String),`display_name` Nullable(String),`description` Nullable(String),`datatype` Nullable(String),`patient_attribute` Nullable(Int32),`priority` Nullable(String),`cancer_study_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE clinical_event (`clinical_event_id` Nullable(Int64),`patient_id` Nullable(Int64),`start_date` Nullable(Int64),`stop_date` Nullable(Int64),`event_type` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE clinical_event_data (`clinical_event_id` Nullable(Int64),`key` Nullable(String),`value` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE clinical_patient (`internal_id` Nullable(Int64),`attr_id` Nullable(String),`attr_value` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE clinical_sample (`internal_id` Nullable(Int64),`attr_id` Nullable(String),`attr_value` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE cna_event (`cna_event_id` Nullable(Int64),`entrez_gene_id` Nullable(Int64),`alteration` Nullable(Int32)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE copy_number_seg (`seg_id` Nullable(Int64),`cancer_study_id` Nullable(Int64),`sample_id` Nullable(Int64),`chr` Nullable(String),`start` Nullable(Int64),`end` Nullable(Int64),`num_probes` Nullable(Int64),`segment_mean` Nullable(Float64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE copy_number_seg_file (`seg_file_id` Nullable(Int64),`cancer_study_id` Nullable(Int64),`reference_genome_id` Nullable(String),`description` Nullable(String),`filename` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE data_access_tokens (`token` Nullable(String),`username` Nullable(String),`expiration` Nullable(DateTime64(6)),`creation` Nullable(DateTime64(6))) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE gene (`entrez_gene_id` Nullable(Int64),`hugo_gene_symbol` Nullable(String),`genetic_entity_id` Nullable(Int64),`type` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE gene_alias (`entrez_gene_id` Nullable(Int64),`gene_alias` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE gene_panel (`internal_id` Nullable(Int64),`stable_id` Nullable(String),`description` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE gene_panel_list (`internal_id` Nullable(Int64),`gene_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE generic_entity_properties (`id` Nullable(Int64),`genetic_entity_id` Nullable(Int64),`name` Nullable(String),`value` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE geneset (`id` Nullable(Int64),`genetic_entity_id` Nullable(Int64),`external_id` Nullable(String),`name` Nullable(String),`description` Nullable(String),`ref_link` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE geneset_gene (`geneset_id` Nullable(Int64),`entrez_gene_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE geneset_hierarchy_leaf (`node_id` Nullable(Int64),`geneset_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE geneset_hierarchy_node (`node_id` Nullable(Int64),`node_name` Nullable(String),`parent_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE genetic_alteration (`genetic_profile_id` Int64,`genetic_entity_id` Int64,`values` String ) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY (genetic_profile_id,genetic_entity_id) SETTINGS index_granularity = 8192
CREATE TABLE genetic_entity (`id` Nullable(Int64),`entity_type` Nullable(String),`stable_id` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE genetic_profile (`genetic_profile_id` Nullable(Int64),`stable_id` Nullable(String),`cancer_study_id` Nullable(Int64),`genetic_alteration_type` Nullable(String),`generic_assay_type` Nullable(String),`datatype` Nullable(String),`name` Nullable(String),`description` Nullable(String),`show_profile_in_analysis_tab` Nullable(Int32),`pivot_threshold` Nullable(Float64),`sort_order` Nullable(String),`patient_level` Nullable(Int32)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE genetic_profile_link (`referring_genetic_profile_id` Nullable(Int64),`referred_genetic_profile_id` Nullable(Int64),`reference_type` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE genetic_profile_samples (`genetic_profile_id` Nullable(Int64),`ordered_sample_list` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE gistic (`gistic_roi_id` Nullable(Int64),`cancer_study_id` Nullable(Int64),`chromosome` Nullable(Int64),`cytoband` Nullable(String),`wide_peak_start` Nullable(Int64),`wide_peak_end` Nullable(Int64),`q_value` Nullable(Float64),`amp` Nullable(Int32)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE gistic_to_gene (`gistic_roi_id` Nullable(Int64),`entrez_gene_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE info (`db_schema_version` Nullable(String),`geneset_version` Nullable(String),`derived_table_schema_version` Nullable(String),`gene_table_version` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE mut_sig (`cancer_study_id` Nullable(Int64),`entrez_gene_id` Nullable(Int64),`rank` Nullable(Int64),`NumBasesCovered` Nullable(Int64),`NumMutations` Nullable(Int64),`p_value` Nullable(Float64),`q_value` Nullable(Float64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE mutation (`mutation_event_id` Int64 COMMENT 'References mutation_event.mutation_event_id.',`genetic_profile_id` Int64 COMMENT 'References genetic_profile.genetic_profile_id.',`sample_id` Int64 COMMENT 'References sample.internal_id.',`entrez_gene_id` Int64 COMMENT 'References gene.entrez_gene_id.',`center` Nullable(String) COMMENT 'Center where sequencing was performed.',`sequencer` Nullable(String) COMMENT 'Sequencing platform used.',`mutation_status` Nullable(String) COMMENT 'Mutation status: Germline,Somatic,or LOH.',`validation_status` Nullable(String) COMMENT 'Validation status.',`tumor_seq_allele1` Nullable(String) COMMENT 'Tumor allele 1 sequence.',`tumor_seq_allele2` Nullable(String) COMMENT 'Tumor allele 2 sequence.',`matched_norm_sample_barcode` Nullable(String) COMMENT 'Matched normal sample barcode.',`match_norm_seq_allele1` Nullable(String) COMMENT 'Matched normal allele 1 sequence.',`match_norm_seq_allele2` Nullable(String) COMMENT 'Matched normal allele 2 sequence.',`tumor_validation_allele1` Nullable(String) COMMENT 'Tumor validation allele 1 sequence.',`tumor_validation_allele2` Nullable(String) COMMENT 'Tumor validation allele 2 sequence.',`match_norm_validation_allele1` Nullable(String) COMMENT 'Matched normal validation allele 1.',`match_norm_validation_allele2` Nullable(String) COMMENT 'Matched normal validation allele 2.',`verification_status` Nullable(String) COMMENT 'Verification status.',`sequencing_phase` Nullable(String) COMMENT 'Sequencing phase.',`sequence_source` Nullable(String) COMMENT 'Source of sequencing data.',`validation_method` Nullable(String) COMMENT 'Validation method used.',`score` Nullable(String) COMMENT 'Score or quality metric.',`bam_file` Nullable(String) COMMENT 'Associated BAM file.',`tumor_alt_count` Nullable(Int64) COMMENT 'Tumor alternate allele count.',`tumor_ref_count` Nullable(Int64) COMMENT 'Tumor reference allele count.',`normal_alt_count` Nullable(Int64) COMMENT 'Normal alternate allele count.',`normal_ref_count` Nullable(Int64) COMMENT 'Normal reference allele count.',`amino_acid_change` Nullable(String) COMMENT 'Amino acid change from mutation.',`annotation_json` Nullable(String) COMMENT 'JSON-formatted annotations.' ) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY (genetic_profile_id,entrez_gene_id) SETTINGS index_granularity = 8192 COMMENT 'Mutation observations in specific samples and profiles. References mutation_event,gene,genetic_profile,and sample.'
CREATE TABLE mutation_count_by_keyword (`genetic_profile_id` Nullable(Int64),`keyword` Nullable(String),`entrez_gene_id` Nullable(Int64),`keyword_count` Nullable(Int64),`gene_count` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE mutation_event (`mutation_event_id` Nullable(Int64),`entrez_gene_id` Nullable(Int64),`chr` Nullable(String),`start_position` Nullable(Int64),`end_position` Nullable(Int64),`reference_allele` Nullable(String),`tumor_seq_allele` Nullable(String),`protein_change` Nullable(String),`mutation_type` Nullable(String),`ncbi_build` Nullable(String),`strand` Nullable(String),`variant_type` Nullable(String),`db_snp_rs` Nullable(String),`db_snp_val_status` Nullable(String),`refseq_mrna_id` Nullable(String),`codon_change` Nullable(String),`uniprot_accession` Nullable(String),`protein_pos_start` Nullable(Int64),`protein_pos_end` Nullable(Int64),`canonical_transcript` Nullable(Int32),`keyword` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE patient (`internal_id` Nullable(Int64),`stable_id` Nullable(String),`cancer_study_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE reference_genome (`reference_genome_id` Nullable(Int64),`species` Nullable(String),`name` Nullable(String),`build_name` Nullable(String),`genome_size` Nullable(Int64),`url` Nullable(String),`release_date` Nullable(DateTime64(6))) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE reference_genome_gene (`entrez_gene_id` Nullable(Int64),`reference_genome_id` Nullable(Int64),`chr` Nullable(String),`cytoband` Nullable(String),`start` Nullable(Int64),`end` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE resource_definition (`resource_id` Nullable(String),`display_name` Nullable(String),`description` Nullable(String),`resource_type` Nullable(String),`open_by_default` Nullable(Int32),`priority` Nullable(Int64),`cancer_study_id` Nullable(Int64),`custom_metadata` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE resource_patient (`internal_id` Nullable(Int64),`resource_id` Nullable(String),`url` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE resource_sample (`internal_id` Nullable(Int64),`resource_id` Nullable(String),`url` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE resource_study (`internal_id` Nullable(Int64),`resource_id` Nullable(String),`url` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE sample (`internal_id` Nullable(Int64),`stable_id` Nullable(String),`sample_type` Nullable(String),`patient_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE sample_cna_event (`cna_event_id` Int64 COMMENT 'References cna_event.cna_event_id.',`sample_id` Int64 COMMENT 'References sample.internal_id.',`genetic_profile_id` Int64 COMMENT 'References genetic_profile.genetic_profile_id.',`annotation_json` Nullable(String) COMMENT 'JSON-formatted annotation details.' ) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') PRIMARY KEY (genetic_profile_id,cna_event_id,sample_id) ORDER BY (genetic_profile_id,cna_event_id,sample_id) SETTINGS index_granularity = 8192 COMMENT 'Observed CNA events per sample and profile. References cna_event,sample,and genetic_profile.'
CREATE TABLE sample_list (`list_id` Nullable(Int64),`stable_id` Nullable(String),`category` Nullable(String),`cancer_study_id` Nullable(Int64),`name` Nullable(String),`description` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE sample_list_list (`list_id` Nullable(Int64),`sample_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE sample_profile (`sample_id` Nullable(Int64),`genetic_profile_id` Nullable(Int64),`panel_id` Nullable(Int64)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE structural_variant (`internal_id` Nullable(Int64),`genetic_profile_id` Nullable(Int64),`sample_id` Nullable(Int64),`site1_entrez_gene_id` Nullable(Int64),`site1_ensembl_transcript_id` Nullable(String),`site1_chromosome` Nullable(String),`site1_region` Nullable(String),`site1_region_number` Nullable(Int64),`site1_contig` Nullable(String),`site1_position` Nullable(Int64),`site1_description` Nullable(String),`site2_entrez_gene_id` Nullable(Int64),`site2_ensembl_transcript_id` Nullable(String),`site2_chromosome` Nullable(String),`site2_region` Nullable(String),`site2_region_number` Nullable(Int64),`site2_contig` Nullable(String),`site2_position` Nullable(Int64),`site2_description` Nullable(String),`site2_effect_on_frame` Nullable(String),`ncbi_build` Nullable(String),`dna_support` Nullable(String),`rna_support` Nullable(String),`normal_read_count` Nullable(Int64),`tumor_read_count` Nullable(Int64),`normal_variant_count` Nullable(Int64),`tumor_variant_count` Nullable(Int64),`normal_paired_end_read_count` Nullable(Int64),`tumor_paired_end_read_count` Nullable(Int64),`normal_split_read_count` Nullable(Int64),`tumor_split_read_count` Nullable(Int64),`annotation` Nullable(String),`breakpoint_type` Nullable(String),`connection_type` Nullable(String),`event_info` Nullable(String),`class` Nullable(String),`length` Nullable(Int64),`comments` Nullable(String),`sv_status` Nullable(String),`annotation_json` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE type_of_cancer (`type_of_cancer_id` Nullable(String),`name` Nullable(String),`dedicated_color` Nullable(String),`short_name` Nullable(String),`parent` Nullable(String)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
CREATE TABLE users (`email` Nullable(String),`name` Nullable(String),`enabled` Nullable(Int32)) ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}','{replica}') ORDER BY tuple() SETTINGS index_granularity = 8192
INSERT INTO info (`db_schema_version`, `geneset_version`, `derived_table_schema_version`, `gene_table_version`) VALUES ('2.14.5', 'msigdb_v2025.1.Hs', '1.0.9', 'hgnc_v7_2025.10.7');
